onlyBuiltDependencies:
  - '@serialport/bindings-cpp'
  - core-js
  - core-js-pure
  - electron
  - electron-winstaller
  - usb

overrides:
  wbm-usb-device: link:../../../node modules/wbm-usb-device
